### ISSUE TITLE
Show recipes for herbs on their seeds

### ISSUE THREAD

**Issue by hawkins** [skiclimbcode/herblore-recipes#3]
Hey, love the plugin! As soon as I had it installed I wondered how I ever played without it.

However, I'm playing a UIM and on a long grind to farm seeds, so I'm often wondering what a seed is good for - i.e., if I have kwuarm seeds, what can I make with kwuarm weeds, and should I keep them? To that end, I would love an option to support showing recipes for an herb from its seed! Is that something you could support? I could try to PR it if you would like

**Comment by skiclimbcode** [comment]
That can absolutely be added!
I wrote this plugin fairly quickly and so the architecture of it is a bit wonky. I'm trying to decide if I should spend some time re-writing it so that it's no longer using the enum as basically the source of data for everything... But that'll take quite some time, so until then I can add support for this within a day or two (balancing work atm).

If you don't want to wait and are willing to get frustrated by my code, feel free to have a crack at it :).

Sidenote: I'm also waiting on the RuneLite guys to approve an update PR that will add the tooltip to finished potions, showing the ingredients required for that potion.

**Comment by skiclimbcode** [comment]
@hawkins Hey! I've added the feature, linked the PR with this issue to easily reference it. Still no refactoring of the foundational structure of the plugin ;) but it works!

**Comment by skiclimbcode** [comment]
Leaving issue open until PR is merged with RuneLite

**Comment by hawkins** [comment]
Woah! That turnaround! Thanks so much, that’s so awesome 😄

**Comment by hawkins** [comment]
Works amazing. Thanks again! 🥳
